### ISSUE TITLE
python major version

### ISSUE THREAD

**Issue by NightFantomJ2** [PyUserInput/PyUserInput#25] opened 2017-08-06 16:55 UTC
I couldn't find a mention of whether this is intended for python 2 or 3, so I hoped it was agnostic or meant for 3. Installing crashed on "SyntaxError: Missing parentheses in call to 'print'" so I guess it was meant for python 2.

Assumption: made for python 2.
Issue: no mention of python 2 in readme.
Suggestion: add "python 2" in the readme.

Alternate assumption: made version agnostic.
Issue: bug in setup.py (or deeper in the code) crashing for python 3.
Suggestion: fix print lines?

**Comment by pepijndevos** [comment] 2017-08-09 07:32
I'm in favor of Python 3 compatibility, obviously.
Question is if it's just the print statements or deeper problems.
Also note that I recently merged a PR that replaces the debug printing with proper logging, does that fix your problem?

**Comment by kristoff-it** [comment] 2017-08-10 13:20
I have used it a couple of days ago from python 3.6.1 on OSX (downloading the latest version from pip), so I'd say that there should not be any major compatibility problem on this platform.

@CostantiniMatteo used it on Windows around the same time and he too had no problem there (except the usual Windows dependencies headaches), so that platform should be OK too.

All in all is seems that there are no python2/3 syntax problems (the modules would not install or import in that case) and the basic functionality is confirmed (both for pykeyboard and pymouse) to be there on these two platforms.

**Comment by pepijndevos** [comment] 2017-08-10 13:23
@NightFantomJ2 which version did you use?

I'm going to close this, as it seems to be fixed in master with the logging change. If you're still having problems with master, please reopen.

**Closed by pepijndevos** 2017-08-10 13:23 UTC

**Comment by NightFantomJ2** [comment] 2017-08-12 17:30
It seems that the issue is not in PyUserInput but in whatever dependant libraries it's calling on, more specifically while installing pywin32 (which I'm sure is already installed, but maybe not where he wants it?)

Pastebin with the output if it helps, I've redownloaded the latest zip from this github, and I'm trying to install it to my anaconda environment. I've never done this before to be honest so chances are that I'm doing something stupid :stuck_out_tongue: 
https://pastebin.com/RpRbPQuv
